# Generated by Django 5.1.3 on 2024-12-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=255)),
                ('opis', models.TextField(help_text='Krótka charakterystyka typu miodu', max_length=1000)),
                ('miody_foto', models.ImageField(upload_to='miody_foto')),
            ],
        ),
    ]
