# Generated by Django 4.2.7 on 2024-09-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=255)),
                ('opis', models.TextField(help_text='Krótka charakterystyka typu miodu', max_length=1000)),
                ('foto', models.ImageField(upload_to='media/miody/')),
            ],
        ),
    ]
