# Generated by Django 5.1.3 on 2025-01-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miody',
            name='miody_foto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='miody_foto'),
        ),
    ]
