# Generated by Django 5.1.3 on 2025-01-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0002_alter_miody_miody_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miody',
            name='miody_foto',
            field=models.ImageField(blank=True, default='miody_foto/spadz.jpg', null=True, upload_to='miody_foto'),
        ),
    ]
